This is makeindex, version 2.14 [02-Oct-2002] (kpathsea + Thai support).
Scanning style file Tesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Tesis.acn....done (440 entries accepted, 0 rejected).
Sorting entries......done (4461 comparisons).
Generating output file Tesis.acr....done (189 lines written, 0 warnings).
Output written in Tesis.acr.
Transcript written in Tesis.alg.
